on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 verificar:
   runs-on: ubuntu-latest

   steps:
     - name: Baixar código do repositório
       uses: actions/checkout@v4

     - name: Mostrar arquivos da pasta
       run: ls -la

     - name: Validar se existe README
       run: test -f README.md

     - name: Mensagem final
       run: echo "Projeto verificado com sucesso!"
